// <auto-generated />
namespace Proyecto1._1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class alv3435 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(alv3435));
        
        string IMigrationMetadata.Id
        {
            get { return "201806150029015_alv3435"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
