// <auto-generated />
namespace Proyecto1._1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addMateria_UAP : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addMateria_UAP));
        
        string IMigrationMetadata.Id
        {
            get { return "201805241525162_addMateria_UAP"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
