// <auto-generated />
namespace Proyecto1._1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class loquesea23 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(loquesea23));
        
        string IMigrationMetadata.Id
        {
            get { return "201806071432481_loquesea2.3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
